<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Pesan extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model(array('Saldo_model','Tagihan_siswa_kls_model','Jn_tagihan_model','Kelas_siswa_model','Siswa_model','Kelas_model','Pembayaran_model','User_model','Th_akademik_model','Pesan_model'));
        $this->load->library(array('form_validation','upload','image_lib','template','session'));
        $this->load->helper(array('form', 'url', 'html'));

        $session_jabatan=$this->session->userdata('nama_jabatan');
        if($session_jabatan!='admin TU'){
            redirect('user');
        }

    }

    public function buat_pesan()
    {
      $data = array(
        'page_header' => 'pesan',
        'active'      =>'',
        'action'      =>site_url('pesan/pesan'),
      );

      $this->template->display('siswa/pesan_form',$data);
    }

    public function pesan()
    {
      $bln=Date('m');
      if ($bln==12 || $bln==6) {
        $data=$this->Pesan_model->cr_blm_lunas_all($bln)->result();
      }else{
        $data=$this->Pesan_model->cr_blm_lunas_spp($bln)->result();
      }
      


      foreach ($data as $key) {
        $pesan = array(
          'nis' => $key->nis,
          'isi_pesan' => $this->input->post('isi_pesan',TRUE),
          'tgl' => Date('d-m-Y'),
        );
         $this->Pesan_model->insert($pesan);
      }

      $this->session->set_flashdata('message', '(Pesan Berhasil terkirim..)');
      redirect('pesan/buat_pesan');
    }






}

/* End of file Kelas.php */
/* Location: ./application/controllers/Kelas.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-12-06 05:39:44 */
/* http://harviacode.com */
