<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Kelas_model extends CI_Model
{

    public $table = 'kelas';
    public $id = 'id_kelas';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by("tingkat", "ASC");
        return $this->db->get($this->table)->result();
    }

    function get_all_exc()
    {
        $this->db->order_by("kelas.tingkat, kelas.nama_kelas");
        $this->db->where_not_in('tingkat',0);
        return $this->db->get($this->table)->result();
    }

    function grup_kls()
    {
        $this->db->order_by("kelas.tingkat, kelas.nama_kelas");
        $this->db->where_not_in('tingkat',0);
        $this->db->group_by('tingkat');
        return $this->db->get($this->table)->result();
    }


    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    function get_by_id2($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table);
    }

    function cari_kelas($kls,$nm)
    {
      $this->db->like('tingkat',$kls);
      $this->db->like('nama_kelas',$nm);
      $this->db->order_by('nama_kelas');
      return $this->db->get($this->table)->result();
    }

    function cari_kelas2($kls,$nm)
    {
      $this->db->like('tingkat',$kls);
      $this->db->where('nama_kelas',$nm);
      return $this->db->get($this->table)->row();
    }



    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_kelas', $q);
	$this->db->or_like('nama_kelas', $q);
	$this->db->or_like('tingkat', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_kelas', $q);
	$this->db->or_like('nama_kelas', $q);
	$this->db->or_like('tingkat', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Kelas_model.php */
/* Location: ./application/models/Kelas_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-12-06 05:39:44 */
/* http://harviacode.com */
