<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Pembayaran_model extends CI_Model
{

    public $table = 'pembayaran';
    public $id = 'id_pembayaran';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    function get_by_nis($nis)
    {
      $this->db->join('jn_tagihan','pembayaran.id_jn_tagihan = jn_tagihan.id_jn_tagihan');
      $this->db->join('th_akademik','pembayaran.th_akademik = th_akademik.id_th_akademik');
      $this->db->where('Pembayaran.nis', $nis);
      $this->db->where('th_akademik.status',1);
      return $this->db->get($this->table)->result();
    }



    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_pembayaran', $q);
	$this->db->or_like('nis', $q);
	$this->db->or_like('id_jn_tagihan', $q);
	$this->db->or_like('nominal_bayar', $q);
	$this->db->or_like('tgl', $q);
	$this->db->or_like('ket', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    function jumlah_data()
    {
      $this->db->select('COUNT(DISTINCT tmp.briva) AS jml_data');
      return $this->db->get('tmp');
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_pembayaran', $q);
	$this->db->or_like('nis', $q);
	$this->db->or_like('id_jn_tagihan', $q);
	$this->db->or_like('nominal_bayar', $q);
	$this->db->or_like('tgl', $q);
	$this->db->or_like('ket', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    function bayar_excel_total()
    {
      $this->db->select('SUM(tmp.jumlah) AS total');
      $this->db->from('tmp');
      $this->db->group_by('briva');
      return $this->db->get();
    }
    function bayar_excel_id()
    {
      $this->db->select('briva');
      $this->db->from('tmp');
      $this->db->group_by('briva');
      return $this->db->get();
    }

}

/* End of file Pembayaran_model.php */
/* Location: ./application/models/Pembayaran_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-12-06 05:39:44 */
/* http://harviacode.com */
