<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Th_akademik_model extends CI_Model
{

    public $table = 'th_akademik';
    public $id = 'id_th_akademik';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }


    function th_aktif()
    {
        $this->db->select('*');
        $this->db->from('th_akademik');
        $this->db->where('status',1);
        $query = $this->db->get();
        return $query;
    }

    function id_th_aktif()
    {
        $this->db->where('status',1);
        return $this->db->get($this->table)->row();
    }

    function cek_th_aktif($data)
    {
      $this->db->where('id_th_akademik',$data['id_th_akademik']);
      $this->db->where('status',1);
      return $this->db->get($this->table);
    }

    function cari_siswa_kelas($th_aktif)
    {
      $this->db->join('kelas_siswa','th_akademik.id_th_akademik=kelas_siswa.id_th_akademik');
      $this->db->join('siswa','kelas_siswa.nis = siswa.nis');
      $this->db->join('kelas','kelas_siswa.id_kelas = kelas.id_kelas');
      $this->db->where('th_akademik.id_th_akademik',$th_aktif);
      // $this->db->where('kelas.id_kelas','k2');
      return $this->db->get($this->table);
    }

    function cek_siswa_kelas($nis,$th_aktif)
    {
      $this->db->join('kelas_siswa','th_akademik.id_th_akademik=kelas_siswa.id_th_akademik');
      $this->db->join('siswa','kelas_siswa.nis = siswa.nis');
      $this->db->join('kelas','kelas_siswa.id_kelas = kelas.id_kelas');
      $this->db->where('th_akademik.id_th_akademik',$th_aktif);
      $this->db->where('kelas_siswa.nis',$nis);
      return $this->db->get($this->table);
    }
    // get all
    function get_all()
    {
      $this->db->select('*');
      $this->db->from('th_akademik');
      $query = $this->db->get();
      return $query;
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    function count_row()
    {
      $this->db->from($this->table);
      return $this->db->count_all_results();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_th_akademik', $q);
	$this->db->or_like('tahun', $q);
	$this->db->or_like('semester', $q);
	$this->db->or_like('status', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_th_akademik', $q);
	$this->db->or_like('tahun', $q);
	$this->db->or_like('semester', $q);
	$this->db->or_like('status', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data, $data2)
    {
      $this->db->where('status',1);
      $this->db->update($this->table,$data2);

        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Th_akademik_model.php */
/* Location: ./application/models/Th_akademik_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-12-06 05:39:45 */
/* http://harviacode.com */
